# Script to filter the tif files generated by NDVI.py based on NDVI values
# Refer to studies to determine the desired range of NDVI values for filtering (e.g., 0.4 < NDVI)

# Import libraries
import glob
import os
import re
from osgeo import gdal  


# Define a function to calculate NDVI values
def ndvi(red, nir):
    try:
        return ((nir - red)/(nir + red))
    except Exception as e:
        print("Error: " + str(e))


def filter_ndvi_values(path):
    print("Filtering NDVI values...")

    # Set input directory
    in_dir = path

    # Regex to capture the bands and their extensions
    pattern = re.compile(r'.*_(B\d{2})_\d+m\.tif$|.*_(B\d{2})\.jp2$')

    # Get lists containing each band that will be iterated over later
    red_files = glob.glob(os.path.join(in_dir, '**'), recursive=True)
    red_files = [band for band in red_files if pattern.match(
        band) and 'B04' in band]

    nir_files = glob.glob(os.path.join(in_dir, '**'), recursive=True)
    nir_files = [band for band in nir_files if pattern.match(
        band) and 'B08' in band]

    for i in range(len(red_files)):

        # Open each band using gdal
        red_link = gdal.Open(red_files[i])
        nir_link = gdal.Open(nir_files[i])

        # Read each band as an array and convert it to float for calculations
        red = red_link.ReadAsArray().astype(float)
        nir = nir_link.ReadAsArray().astype(float)

        # Call the ndvi() function on red, NIR bands
        ndvi2 = ndvi(red, nir)

        # Output filename
        outfile_name = red_files[i].split('_B')[0] + '_NDVI_Filtered.tif'

        # Boolean matrix
        ndvi_mask = (ndvi2 >= -0.153) & (ndvi2 <= -0.046)

        # Convert matrix to mask
        ndvi_threshold = ndvi_mask.astype(int)

        x_pixels = ndvi2.shape[0]  # number of pixels in x
        y_pixels = ndvi2.shape[1]  # number of pixels in y

        # Set up output GeoTIFF
        driver = gdal.GetDriverByName('GTiff')

        # Create driver using the output filename, x and y pixels, # of bands, and datatype
        ndvi_data = driver.Create(
            outfile_name, x_pixels, y_pixels, 1, gdal.GDT_Byte)

        # Set NDVI array as the 1 output raster band
        ndvi_data.GetRasterBand(1).WriteArray(ndvi_threshold)

        # Set up the coordinate reference system of the output GeoTIFF
        geotrans = red_link.GetGeoTransform()  # Grab input GeoTranform information
        proj = red_link.GetProjection()  # Grab projection information from the input file

        # Set the GeoTransform parameters and projection on the output file
        ndvi_data.SetGeoTransform(geotrans)
        ndvi_data.SetProjection(proj)
        ndvi_data.FlushCache()
        ndvi_data = None


if __name__ == '__main__':

    path = input(
        "Enter the path where the images are located to filter them based on a specific range of NDVI values: ")

    filter_ndvi_values(path)
